### ISSUE TITLE
TLS-SRP (client) support

### ISSUE THREAD

**Issue by SoniEx2** [noxxi/p5-io-socket-ssl#104]
Hello!

Would it be possible to have TLS-SRP support, as a client?

Thanks.

**Comment by noxxi** [comment]
IO::Socket::SSL is a Perl layer on top of Net::SSLeay, which provides the interface to the OpenSSL API. There is currently no support for any SRP related API in Net::SSLeay, so there is nothing SRP support in IO::Socket::SSL could be based on. This means that currently this functionality will not be implemented.
