### ISSUE TITLE
Failed to compile perl-IO-Socket-SSL-1.94-7

### ISSUE THREAD

**Issue by fishANDdog** [noxxi/p5-io-socket-ssl#114]
For some reason, I need to compile perl-IO-Socket-SSL-1.94-7.   After compilation, there are errors in the process of testing, resulting in the final compilation failure. How can i solve it?  I compiled this in CentOS 7.

`Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.kfkeu1
+ umask 022
+ cd /builddir/build/BUILD
+ '[' /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch '!=' / ']'
+ rm -rf /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch
++ dirname /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch
+ mkdir -p /builddir/build/BUILDROOT
+ mkdir /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch
+ cd IO-Socket-SSL-1.94
+ make pure_install DESTDIR=/builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch
Installing /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch/usr/share/perl5/vendor_perl/IO/Socket/SSL.pm
Installing /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch/usr/share/perl5/vendor_perl/IO/Socket/SSL/Intercept.pm
Installing /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch/usr/share/perl5/vendor_perl/IO/Socket/SSL/Utils.pm
Installing /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch/usr/share/man/man3/IO::Socket::SSL.3pm
Installing /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch/usr/share/man/man3/IO::Socket::SSL::Utils.3pm
Installing /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch/usr/share/man/man3/IO::Socket::SSL::Intercept.3pm
+ find /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch -type f -name .packlist -exec rm -f '{}' +
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /builddir/build/BUILDROOT/perl-IO-Socket-SSL-1.94-7.cu.noarch
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 50000000 /builddir/build/BUILD/IO-Socket-SSL-1.94
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.pKRpwo
+ umask 022
+ cd /builddir/build/BUILD
+ cd IO-Socket-SSL-1.94
+ make test
+ make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01loadmodule.t ........... ok
t/02settings.t ............. ok
t/acceptSSL-timeout.t ...... ok
t/auto_verify_hostname.t ...
Failed 16/30 subtests
t/cert_no_file.t ........... ok
t/compatibility.t .......... ok
t/connectSSL-timeout.t ..... ok
t/core.t ...................
Failed 47/52 subtests
t/dhe.t .................... ok
t/ecdhe.t .................. ok
t/io-socket-inet6.t ........ skipped: no IO::Socket::INET6 available
t/io-socket-ip.t ........... ok
t/memleak_bad_handshake.t .. ok
t/mitm.t ...................
Failed 6/8 subtests
t/nonblock.t ............... ok
t/npn.t .................... ok
t/readline.t ............... ok
t/sessions.t ...............
Failed 27/35 subtests
t/signal-readline.t ........ ok
Can't call method "get_servername" on an undefined value at t/sni.t line 83.
Can't call method "verify_hostname" without a package or object reference at t/sni.t line 74.
t/sni.t ....................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 16/17 subtests
t/start-stopssl.t .......... ok
t/startssl-failed.t ........ ok
t/startssl.t ............... ok
t/sysread_write.t .......... ok
t/verify_hostname.t ........ ok
Test Summary Report
-------------------
t/auto_verify_hostname.t (Wstat: 0 Tests: 22 Failed: 8)
  Failed tests:  3, 5-6, 8, 12, 16, 18, 22
  Parse errors: Bad plan.  You planned 30 tests but ran 22.
t/core.t                 (Wstat: 13 Tests: 6 Failed: 1)
  Failed test:  6
  Non-zero wait status: 13
  Parse errors: Bad plan.  You planned 52 tests but ran 6.
t/mitm.t                 (Wstat: 0 Tests: 3 Failed: 1)
  Failed test:  3
  Parse errors: Bad plan.  You planned 8 tests but ran 3.
t/sessions.t             (Wstat: 0 Tests: 10 Failed: 2)
  Failed tests:  9-10
  Parse errors: Bad plan.  You planned 35 tests but ran 10.
t/sni.t                  (Wstat: 65280 Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 17 tests but ran 3.
Files=25, Tests=255, 38 wallclock secs ( 0.10 usr  0.03 sys +  1.64 cusr  0.37 csys =  2.14 CPU)
Result: FAIL
Failed 5/25 test programs. 14/255 subtests failed.
make: *** [test_dynamic] Error 255
`

**Comment by noxxi** [comment]
1.94 is nearly 9 years old, recent is 2.074 (about a month old). If you insist on running such an old software version, you are on your own, i.e. no support for this.
