### ISSUE TITLE
When will 2.075 hit CPAN?

### ISSUE THREAD

**Issue by matthewpersico** [noxxi/p5-io-socket-ssl#116]
My $job uses DPKG handling and would prefer to grab the 2.075 tarball from CPAN instead of trying to import a github repo. Are there plans to release this version to CPAN?

Thank you

**Comment by noxxi** [comment]
Thanks for asking. I did not realize that something went wrong uploading the release a while ago. Just uploaded it successfully.

**Comment by matthewpersico** [comment]
Thank you so much!
