### ISSUE TITLE
Use of uninitialized value $2 in concatenation (.) or string at /usr/local/lib/perl5/site_perl/IO/Socket/SSL.pm line 792.

### ISSUE THREAD

**Issue by BeerStud** [noxxi/p5-io-socket-ssl#126]
FreeBSD.1-RELEASE-p6 GENERIC amd64

After a recent update, I began noticing the following message in the daily run output when running "ddclient":

Forcing ddclient update:
Use of uninitialized value $2 in concatenation (.) or string at /usr/local/lib/perl5/site_perl/IO/Socket/SSL.pm line 792.

All of the UPDATES do succeed, though.

**Comment by noxxi** [comment]
This is likely because some `-w` command line is applying `use warnings` to all of the modules included in ddclient instead of letting each module decide by its own if warnings should be applied or not.

**Comment by noxxi** [comment]
should be solved by locally disabling warnings: 8509e26
