### ISSUE TITLE
Outdated document about the default SSL_version

### ISSUE THREAD

**Issue by skaji** [noxxi/p5-io-socket-ssl#140]
lib/IO/Socket/SSL.pod says

> The default SSL_version is 'SSLv23:!SSLv3:!SSLv2' 

https://github.com/noxxi/p5-io-socket-ssl/blob/master/lib/IO/Socket/SSL.pod?plain=1#L1050

but, I think the default SSL_version is now `SSLv23:!TLSv1:!TLSv1_1:!SSLv3:!SSLv2`.
https://github.com/noxxi/p5-io-socket-ssl/blob/master/lib/IO/Socket/SSL.pm#L200

It would be nice if you could update lib/IO/Socket/SSL.pod too.

**Comment by noxxi** [comment]
Thanks for pointing out this inconsistency. Fixed in 3a6087a

**Comment by skaji** [comment]
@noxxi Thank you!
