### ISSUE TITLE
operator precedence error in IO::Socket::SSL::SSL_Context->new

### ISSUE THREAD

**Issue by mauke** [noxxi/p5-io-socket-ssl#155]
Yesterday's 2.087 release contains an unfortunate bug:
```
$ perl -we 'use IO::Socket::SSL'
Possible precedence issue with control flow operator (return) at /home/mauke/perl5/perlbrew/perls/perl-5.40.0/lib/site_perl/5.40.0/IO/Socket/SSL.pm line 2599.
```

This is caused by the following code:
```perl
			return $psk->{$identity} || $psk->{''} or return
			    IO::Socket::SSL->_internal_error(
			    "no PSK for given identity '$identity' and no default");
```

`or` has lower precedence than `return`, so this parses as `(return $psk->{$identity} || $psk->{''}) or ...`, but the `...` part is unreachable (because `return` never returns).

It should probably be
```perl
			return $psk->{$identity} || $psk->{''} ||
			    IO::Socket::SSL->_internal_error(
			    "no PSK for given identity '$identity' and no default");
```
instead.

(This bug is normally invisible/silent because IO::Socket::SSL doesn't `use warnings` (in an attempt to stay compatible with 5.005?). But if the `-w` command-line switch is used, it switches on default warnings in all code that doesn't `use warnings` explicitly, including modules.)

**Comment by noxxi** [comment]
Thanks for pointing out the problem. It is fixed in 80315ed1
