### ISSUE TITLE
2.087: Compilation failure with perl 5.8.x

### ISSUE THREAD

**Issue by eserte** [noxxi/p5-io-socket-ssl#157]
The perl module does not compile anymore with perl 5.8.9. See http://www.cpantesters.org/cpan/report/a0a9f218-3db8-11ef-a324-efea6d8775ea for a sample fail report.

I see a defined-or (//=) in the diff https://metacpan.org/release/SULLR/IO-Socket-SSL-2.087/diff/SULLR/IO-Socket-SSL-2.086 , so probably that's the reason.

**Comment by noxxi** [comment]
Thanks for reporting. This should be fixed in 2.088
