### ISSUE TITLE
t\verify_hostname_standalone.t #78 fails on Windows 8.1

### ISSUE THREAD

**Issue by nanis** [noxxi/p5-io-socket-ssl#31]
<pre>C:\> prove -vb t\verify_hostname_standalone.t
...
not ok 78 - 1 != 0 |[::4.5.6.9]: cn= san=IP:0000:0000:0000:0000:0000:0000:0405:0609

#   Failed test '1 != 0 |[::4.5.6.9]: cn= san=IP:0000:0000:0000:0000:0000:0000:0405:0609'
#   at t\verify_hostname_standalone.t line 55.
# Looks like you failed 1 test of 78.</pre>

Windows 8.1 Pro 64-bit

OpenSSL 1.0.2a 19 Mar 2015

Visual Studio 2013 tools:

<pre>cl /?
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x64</pre>

<pre>nmake /?
Microsoft (R) Program Maintenance Utility Version 12.00.21005.1</pre>

<pre>Summary of my perl5 (revision 5 version 20 subversion 2) configuration:
   
  Platform:
    osname=MSWin32, osvers=6.3, archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -GF -W3 -O1 -Os -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -DCONSERVATIVE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE  -DUSE_64_BIT_ALL -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO',
    optimize='-O1 -Os -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise',
    cppflags='-DWIN32'
    ccversion='18.00.31101', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='__int64', ivsize=8, nvtype='double', nvsize=8, Off_t='__int64', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\opt\perl-5.20.2\lib\CORE"  -machine:AMD64 "/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"'
    libpth="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\amd64"
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
    libc=msvcrt.lib, so=dll, useshrplib=true, libperl=perl520.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\opt\perl-5.20.2\lib\CORE"  -machine:AMD64 "/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"'

Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES HAVE_INTERP_INTERN MULTIPLICITY
                        PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_IMPLICIT_SYS
                        PERL_MALLOC_WRAP PERL_NEW_COPY_ON_WRITE
                        PERL_PRESERVE_IVUV USE_64_BIT_ALL USE_64_BIT_INT
                        USE_ITHREADS USE_LARGE_FILES USE_LOCALE
                        USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
                        USE_SITECUSTOMIZE
  Built under MSWin32
  Compiled at Feb 16 2015 08:44:56
  %ENV:
    PERLDOC_PAGER="c:\opt\cygwin64\bin\less.exe -+C -E -F -g -i"
  @INC:
    c:/opt/perl-5.20.2/site/lib/MSWin32-x64-multi-thread
    c:/opt/perl-5.20.2/site/lib
    c:/opt/perl-5.20.2/lib
    .</pre>

**Comment by noxxi** [comment]
Thanks for reporting. For me it looks like an issue with inet_pton on your compiler or recent perl version, which accepts not only "IPv6" but also "[IPv6]". Please check if dcc09a52c provides a fixe for your environment.

**Comment by nanis** [comment]
Thanks for the suggestion. Will check and report back.

**Comment by nanis** [comment]
Apologies for the delay. This morning, I got:

<pre>--> Working on S/SU/SULLR/IO-Socket-SSL-2.015.tar.gz
Fetching http://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.015.tar.gz ... OK
Configuring IO-Socket-SSL-2.015 ... OK
Building and testing IO-Socket-SSL-2.015 ... OK
Successfully installed IO-Socket-SSL-2.015</pre>

which I believe incorporates that change.
