### ISSUE TITLE
Bug to get client certificate

### ISSUE THREAD

**Issue by Logioniz** [noxxi/p5-io-socket-ssl#43]
* Perl version: v5.22.1 built for x86_64-linux-gnu-thread-multi
* Operating system: Ubuntu 16.04 LTS
* IO::Socket::SSL: 2.027
* OpenSSL: 1.0.2g-fips  1 Mar 2016

#### Generate keys
```
openssl req  -nodes -new -x509  -keyout server.key -out server.cert
openssl req  -nodes -new -x509  -keyout client.key -out client.cert
```

#### Run server
Get server from examples [ss_server.pl](https://github.com/noxxi/p5-io-socket-ssl/blob/master/example/ssl_server.pl)

```
perl ss_server.pl -d -C server.cert -K server.key 127.0.0.1:3000
```

#### Run client
```
openssl s_client -connect 127.0.0.1:3000 -cert client.cert -key client.key
```

#### Server output
```
perl ss_server.pl -d -C server.cert -K server.key 127.0.0.1:3000
waiting for next connection.
new SSL connection without client certificate
waiting for next connection.
```

**No client certificate**

### Expected behavior
Client certificate must be.

To verify that the certificate is loaded, you can replace the server with openssl
```
openssl s_server -cert server.cert -key server.key -accept 3000 -Verify 1
```

**Comment by noxxi** [comment]
The example server only requests a certificate from the client if option `--ca` is set because only then the certificate can be verified. And if no certificate is requested the client will not send one. I've updated the code to make this more clear in the usage description.

**Comment by Logioniz** [comment]
Thanks, with `--ca` option works.

Can't understand how to get client certificate without verify and not specify client CA. It is possible?
So if i have my own self signed certificate which i want to check on server side. What i must to do?

**Comment by noxxi** [comment]
> Can't understand how to get client certificate without verify and not specify client CA. It is possible?

As documented the certificate is requested if `SSL_verify_mode` is set to `SSL_VERIFY_PEER`. But the way the example programs works is that `SSL_VERIFY_PEER` is only used if option `--ca` is given. This is just an example program and not a full featured test server.

**Comment by Logioniz** [comment]
Oh, my question is not relevant for this example.

For example i have server with `SSL_verify_mode` option. How can i do client request with self signed certificate?
```
#!/usr/bin/perl
use Mojo::Base -strict;

use IO::Socket::SSL;
use DDP;

my $server = IO::Socket::SSL->new(
    # where to listen
    LocalAddr => '127.0.0.1',
    LocalPort => 3000,
    Listen => 10,

    # which certificate to offer
    # with SNI support there can be different certificates per hostname
    SSL_cert_file => 'tls/cert.pem',
    SSL_key_file => 'tls/key.pem',
    SSL_verify_mode => SSL_VERIFY_PEER
) or die "failed to listen: $!";

# accept client
my $client = $server->accept or die
    "failed to accept or ssl handshake: $!,$SSL_ERROR";

warn p $client->peer_certificates;

```

In this example i get `certificate verify failed`, because certificate is self signed.

**Comment by Logioniz** [comment]
Oh, very thanks. Found answer in your documentation. Need to set `SSL_verify_callback` option to validate.
