### ISSUE TITLE
Code with typo is reached when using session_cache

### ISSUE THREAD

**Issue by gabiruh** [noxxi/p5-io-socket-ssl#60]
A mistyped $self is reached when using session_cache:

`my $host = $arg_hash->{PeerAddr} || $arg_hash->{PeerHost}
		    || self->_update_peer;`

https://github.com/noxxi/p5-io-socket-ssl/blob/8e7f7ffc6eb3effc62607d1611e82e470c4d7e19/lib/IO/Socket/SSL.pm#L884

**Comment by noxxi** [comment]
Thanks for reporting. It is fixed in 2.049: https://github.com/noxxi/p5-io-socket-ssl/blob/2.049/lib/IO/Socket/SSL.pm#L884
