### ISSUE TITLE
Memleak when using the CRL feature ($crl not freed !)

### ISSUE THREAD

**Issue by fskale** [noxxi/p5-io-socket-ssl#73]
Hi,
i posted the bug report 2 weeks ago but it hasn't been processed since then.
It's a major bug and should be fixed in time.
I'm sure i'm not the only one to use the CRL feature though.
Link for your convenience:
[https://rt.cpan.org/Public/Bug/Display.html?id=125888](https://rt.cpan.org/Public/Bug/Display.html?id=125888)

Best regards
Franz

**Comment by noxxi** [comment]
closed within b1763e8
