### ISSUE TITLE
Different base class?

### ISSUE THREAD

**Issue by philippe44** [noxxi/p5-io-socket-ssl#82]
Hi - Would it be possible to have the base class as a parameter? One use case is to have SSL connections through SOCKS. To do that currently, I had to duplicate the whole SSL.pm in a new package just to have a different @ISA (IO::Socket::Socks). It works, but such duplication does not feel like the right think to do.

There might be a a much more simple option, but I'm still a Perl noob 

Thanks

**Comment by noxxi** [comment]
There is no need to have a different base class just to use Socks. See [my answer of your question at Stackoverflow](https://stackoverflow.com/questions/55962571/using-iosocketssl-over-an-iosocketsocks-proxy/55964059#55964059) for how to handle this case.
