### ISSUE TITLE
perl-IO-Socket-SSL-1.94   test fail and certs out of date 

### ISSUE THREAD

**Issue by syyhao1994** [noxxi/p5-io-socket-ssl#88]
1.the file of pem in certs are out of date in IO-Socket-SSL-1.94.tar.gz

2.make test failure as showed below

-bash-4.2$ cd IO-Socket-SSL-1.94/
-bash-4.2$ ls
BUGS     MANIFEST   META.yml  Makefile.PL  README.Win32  certs            debuglinks.list    docs          example  pm_to_blib  util
Changes  META.json  Makefile  README       blib          debugfiles.list  debugsources.list  elfbins.list  lib      t
-bash-4.2$ make test
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01loadmodule.t ........... ok   
t/02settings.t ............. ok   
t/acceptSSL-timeout.t ...... Dubious, test returned 1 (wstat 256, 0x100)
Failed 10/15 subtests 
t/auto_verify_hostname.t ... Failed 16/30 subtests 
t/cert_no_file.t ........... ok   
t/compatibility.t .......... 1/9 Can't locate object method "issuer_name" via package "IO::Socket::INET" at t/compatibility.t line 53.
t/compatibility.t .......... Failed 6/9 subtests 
t/connectSSL-timeout.t ..... Dubious, test returned 1 (wstat 256, 0x100)
Failed 10/16 subtests 
t/core.t ................... Failed 47/52 subtests 
t/dhe.t .................... ok   
t/ecdhe.t .................. ok   
t/io-socket-inet6.t ........ skipped: no IO::Socket::INET6 available
t/io-socket-ip.t ........... ok   
t/memleak_bad_handshake.t .. skipped: no usable ps
t/mitm.t ................... Failed 6/8 subtests 
t/nonblock.t ............... 1/27 sysread failed: No such file or directory at t/nonblock.t line 317.
Use of uninitialized value in subroutine entry at /home/abuild/rpmbuild/BUILD/IO-Socket-SSL-1.94/blib/lib/IO/Socket/SSL.pm line 629.
Use of uninitialized value in subroutine entry at /home/abuild/rpmbuild/BUILD/IO-Socket-SSL-1.94/blib/lib/IO/Socket/SSL.pm line 629.
t/nonblock.t ............... Dubious, test returned 2 (wstat 512, 0x200)
Failed 21/27 subtests 
t/npn.t .................... ok   
t/readline.t ............... ok     
t/sessions.t ............... Failed 27/35 subtests 
t/signal-readline.t ........ Failed 1/9 subtests 
t/sni.t .................... 1/17 Can't call method "get_servername" on an undefined value at t/sni.t line 83.
Can't call method "verify_hostname" without a package or object reference at t/sni.t line 74.
t/sni.t .................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 16/17 subtests 
t/start-stopssl.t .......... ok     
t/startssl-failed.t ........ ok   
t/startssl.t ............... ok   
t/sysread_write.t .......... ok   
t/verify_hostname.t ........ ok 

Test Summary Report
-------------------
t/acceptSSL-timeout.t    (Wstat: 256 Tests: 7 Failed: 2)
  Failed tests:  6-7
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 15 tests but ran 7.
t/auto_verify_hostname.t (Wstat: 0 Tests: 22 Failed: 8)
  Failed tests:  3, 5-6, 8, 12, 16, 18, 22
  Parse errors: Bad plan.  You planned 30 tests but ran 22.
t/compatibility.t        (Wstat: 0 Tests: 6 Failed: 3)
  Failed tests:  2, 5-6
  Parse errors: Bad plan.  You planned 9 tests but ran 6.
t/connectSSL-timeout.t   (Wstat: 256 Tests: 8 Failed: 2)
  Failed tests:  7-8
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 16 tests but ran 8.
t/core.t                 (Wstat: 0 Tests: 7 Failed: 2)
  Failed tests:  6-7
  Parse errors: Bad plan.  You planned 52 tests but ran 7.
t/mitm.t                 (Wstat: 0 Tests: 3 Failed: 1)
  Failed test:  3
  Parse errors: Bad plan.  You planned 8 tests but ran 3.
t/nonblock.t             (Wstat: 512 Tests: 17 Failed: 11)
  Failed tests:  6-12, 14-17
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 27 tests but ran 17.
t/sessions.t             (Wstat: 0 Tests: 10 Failed: 2)
  Failed tests:  9-10
  Parse errors: Bad plan.  You planned 35 tests but ran 10.
t/signal-readline.t      (Wstat: 0 Tests: 9 Failed: 1)
  Failed test:  4
t/sni.t                  (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  2-3
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 17 tests but ran 3.
Files=25, Tests=226,  0 wallclock secs ( 0.10 usr  0.04 sys +  1.28 cusr  0.33 csys =  1.75 CPU)
Result: FAIL
Failed 10/25 test programs. 34/226 subtests failed.
make: *** [test_dynamic] Error 2

how can i fix this problem with out update the software? Can i skip these ten test?

**Comment by noxxi** [comment]
1.94 was released more than 6 years ago. I've released lots of new releases since then. I will not support such old releases since they are not intended to be used anymore.

**Comment by syyhao1994** [comment]
> 
> 
> 1.94 was released more than 6 years ago. I've released lots of new releases since then. I will not support such old releases since they are not intended to be used anymore.

Ok, thanks. By the way, dose these expired certs files influence the function of the software or they are only used to test something, as i noticed the whole certs file was install in my /usr/share/doc/perl-IO-Socket-SSL/certs, these private key maybe not safe? Can i delete this file?

**Comment by noxxi** [comment]
These certificates are only used within the test suite, i.e only for `make test`.  They are not intended to be used outside of the test suite. It looks like that at least Fedora Linux copies these certificates also to  /usr/share/doc/perl-IO-Socket-SSL/certs for a reason I don't understand since they don't also copy the tests which use the certificates. It does not do any harm though except for being useless.

**Comment by syyhao1994** [comment]
Thanks a lot!!!!
