### ISSUE TITLE
Tests fails with Openssl 1.1.1-stable branch

### ISSUE THREAD

**Issue by xnox** [noxxi/p5-io-socket-ssl#93]
Tests fails with Openssl 1.1.1-stable branch

I believe this is started with https://github.com/openssl/openssl/commit/db943f43a60d1b5b1277e4b5317e8f288e7a0a3a

Seems like new behaviour happens with EOF, and this trips up io-socket-ssl testsuite.

**Comment by carnil** [comment]
This now has been reported in downstreams (here in Debian as https://bugs.debian.org/954371) after 1.1.1e based version entered unstable.

**Comment by pghmcfc** [comment]
The attached patch is a starting point for getting this working, and needs to be used in conjunction with radiator-software/p5-net-ssleay#161 applied to Net::SSLeay. It's a bit of a hack but it gets the test suite passing for me.
[IO-Socket-SSL-2.067-openssl-1.1.1e.patch.txt](https://github.com/noxxi/p5-io-socket-ssl/files/4363651/IO-Socket-SSL-2.067-openssl-1.1.1e.patch.txt)

**Comment by noxxi** [comment]
I'm not happy with the patch in the current form. It just does something without any kind of information about the underlying issue and it seems to require some strange fix to a test too - which actually means that users might need such strange fixes to their own code too. This is not what users expect.

**Comment by pghmcfc** [comment]
@noxxi, yes I know, which is why I described it as a starting point. It at least indicates where to look for a better fix, which would probably involve checking for the new SSL_R_UNEXPECTED_EOF_WHILE_READING error from OpenSSL so as to be sure about the cause.
As for the test, maybe it really needs fixing in Net::SSLeay but I don't know enough about this code to understand it properly.

**Comment by noxxi** [comment]
Part or even all of the problem seems to come from a behavior change in OpenSSL 1.1.1e which I consider a bug and have filed as such, see https://github.com/openssl/openssl/issues/11388 . I'll wait for a reaction to this bug report before deciding how to best to deal with the issue.

**Comment by noxxi** [comment]
It looks like it is accepted now that OpenSSL 1.1.1e broke some stuff here (affects nginx, Python, ruby...)  and it looks like these changes get reverted. Therefore I check for OpenSSL 1.1.1e now in Makefile.PL and refuse to build when detected: IO::Socket::SSL version 2.068, see 2c124d4. This should work around the problem and hopefully all is fixed again in OpenSSL 1.1.1f.
