### ISSUE TITLE
Installing this hangs and/or fails, an Ubuntu 20.04

### ISSUE THREAD

**Issue by JJ** [noxxi/p5-io-socket-ssl#94]
After having to restart the machine, I did a cpanm install --verbose, and then it failed:

```
t/01loadmodule.t .................. 1/3 
#   Failed test 'loaded'
#   at t/01loadmodule.t line 8.
```

I was starting to seize, so I stopped there

**Comment by noxxi** [comment]
Works without problems for me. Please provide the full output, starting with the exact command you use.

**Comment by JJ** [comment]
I couldn't reproduce it second time I tried. Might have been something temporary. Closing and thanks.
